services:
  - type: web
    name: helplink
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn HelpLink.wsgi:application"
    runtime: "python3.12"
