# Generated by Django 5.2.8 on 2025-11-19 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="helprequest",
            name="category",
            field=models.CharField(
                blank=True, default="Other", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="helprequest",
            name="contact_info",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
    ]
