# Generated by Django 5.2.8 on 2025-11-19 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_helprequest_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="helprequest",
            name="location",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="helprequest",
            name="requester_initials",
            field=models.CharField(blank=True, default="", max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name="helprequest",
            name="requester_name",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="helprequest",
            name="urgency",
            field=models.CharField(
                blank=True,
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                default="low",
                max_length=10,
                null=True,
            ),
        ),
    ]
