# Generated by Django 5.2.6 on 2025-11-11 13:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="avatar",
            field=models.URLField(
                blank=True,
                default="https://crm.lyncotek.com/uploads/no-avatar.png",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_top_helper",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="joined_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userprofile",
            name="reputation_points",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="total_helps",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
